"""
Export the numerical curves of two paper figures as plain "x y" tables that
TikZ reads with `\\draw plot file {...}`, so the numerical panels are drawn in
exactly the same TikZ house style as the schematic figures.

  * Figure fig:nested-vs-iid  (nested vs independent information, 4 panels)
      same computation as generate_paper_figure.py
  * Figure fig:density_limit, bottom row (continuous-limit borrower densities)
      same computation and calibration as plot_density_panels() in credit_model.py

Output: Peter-Pablo-Maryam/figures/tikzdata/
  fig7*.dat, fig6*.dat   one continuous curve per file, already in panel units
  fig7_marks.tex, fig6_marks.tex   \\def macros with panel-unit positions of
                                    thresholds, levels and atoms

Panel units: every panel is drawn on x in [0,1] with arrow axes to 1.05; the
y values are scaled here so the tallest object sits near 0.95 (0.9 for
quantities normalised to 1, matching the prior height used in the TikZ
schematics).  Curves are thinned with Ramer-Douglas-Peucker at a tolerance far
below print resolution, so steps stay sharp and files stay small.

generate_paper_figure.py and plot_density_panels() are left untouched.
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import credit_model as cm  # noqa: E402

OUT = os.path.normpath(os.path.join(HERE, '..', '..', '..', '..',
                                    'Peter-Pablo-Maryam', 'figures', 'tikzdata'))
TOL = 5e-4          # RDP tolerance in panel units (1 unit = 6 cm in the paper)


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def rdp_keep(x, y, tol):
    """Boolean mask of the points kept by Ramer-Douglas-Peucker."""
    n = len(x)
    keep = np.zeros(n, dtype=bool)
    if n == 0:
        return keep
    keep[0] = keep[-1] = True
    stack = [(0, n - 1)]
    while stack:
        i, j = stack.pop()
        if j <= i + 1:
            continue
        xs, ys = x[i + 1:j], y[i + 1:j]
        dx, dy = x[j] - x[i], y[j] - y[i]
        seg = np.hypot(dx, dy)
        if seg == 0.0:
            d = np.hypot(xs - x[i], ys - y[i])
        else:
            d = np.abs(dy * (xs - x[i]) - dx * (ys - y[i])) / seg
        k = int(np.argmax(d))
        if d[k] > tol:
            m = i + 1 + k
            keep[m] = True
            stack.append((i, m))
            stack.append((m, j))
    return keep


def write_curve(name, x, y, note=''):
    """Write one continuous curve (panel units) to OUT/name.dat."""
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)
    x, y = x[ok], y[ok]
    keep = rdp_keep(x, y, TOL)
    path = os.path.join(OUT, name + '.dat')
    with open(path, 'w', newline='\n') as f:
        f.write(f'# {name}: {note}\n' if note else f'# {name}\n')
        f.write('# generated by export_tikz_data.py -- panel units, do not edit\n')
        for xi, yi in zip(x[keep], y[keep]):
            f.write(f'{xi:.5f} {yi:.5f}\n')
    return int(keep.sum())


def write_marks(fname, marks, header):
    """Write \\def macros (panel units) with the raw value as a comment."""
    path = os.path.join(OUT, fname)
    with open(path, 'w', newline='\n') as f:
        f.write(f'% {header}\n')
        f.write('% generated by export_tikz_data.py -- panel units, do not edit\n')
        for key, (val, raw) in marks.items():
            f.write(f'\\def\\{key}{{{val:.5f}}}% raw {raw:.6g}\n')


# ---------------------------------------------------------------------------
# Figure fig:nested-vs-iid
# ---------------------------------------------------------------------------
def export_fig7():
    params = cm.Parameters()
    nested = cm.solve_nested_analytical(params)
    iid = cm.solve_iid(params)
    avg_n, avg_i, _, _ = cm.compute_avg_good_rate(params, nested, iid)

    a0, a1, a2 = nested['alpha0'], nested['alpha1'], nested['alpha2']
    rp, rNS, WNS = nested['rp'], nested['r_NS'], nested['WNS']
    K1 = cm.cfun(1.0) + params.Pi
    goodleft, badleft = nested['goodleftover_alpha2'], nested['badleftover']
    gNS = goodleft / (goodleft + badleft) if goodleft + badleft > 1e-12 else 0.0
    segs = cm._iid_segments(iid)
    ae = iid['alpha_eq']

    print('Figure nested-vs-iid')
    print(f'  alpha0={a0:.4f} alpha1={a1:.4f} alpha2={a2:.4f} '
          f'rp={rp:.4f} r_NS={rNS:.4f} K(1)={K1:.4f}')
    print(f'  iid alpha0={iid["alpha0"]:.4f} alpha_bar={iid["alpha_bar"]:.4f} '
          f'case={iid["case"]} gaps={iid["gaps"]}')
    print(f'  avg good rate: nested={avg_n:.4f} iid={avg_i:.4f}')

    # (A) interest rate ----------------------------------------------------
    sA = 0.95 / K1
    write_curve('fig7A_nested_R1', [a0, a1], [rp * sA, rp * sA], 'nested r, Region I')
    aR2 = np.linspace(a1, a2, 400)
    write_curve('fig7A_nested_R2', aR2, (cm.cfun(aR2) + params.Pi) * sA,
                'nested r, Region II')
    for k, s in enumerate(segs):
        write_curve(f'fig7A_iid_{k}', ae[s], iid['r_eq'][s] * sA, 'iid r')

    # (B) repayment probability ---------------------------------------------
    sB = 0.9
    write_curve('fig7B_nested_R1', nested['alphas_R1'], nested['gammas_R1'] * sB,
                'nested gamma, Region I')
    write_curve('fig7B_nested_R2', nested['alphas_R2'], nested['gammas_R2'] * sB,
                'nested gamma, Region II')
    for k, s in enumerate(segs):
        write_curve(f'fig7B_iid_{k}', ae[s], iid['gamma_eq'][s] * sB, 'iid gamma')

    # (C) cumulative capital ------------------------------------------------
    Wn_x = np.concatenate([[0.0, a0], nested['alphas_R1'], nested['alphas_R2']])
    Wn_y = np.concatenate([[WNS, WNS], WNS + nested['W_cumsum_R1'],
                           WNS + nested['W_R2_cumsum']])
    Wi_x = np.concatenate([[0.0, iid['alpha0']], ae])
    Wi_y = np.concatenate([[0.0, 0.0], iid['W_cumsum']])
    sC = 0.95 / max(np.nanmax(Wn_y), np.nanmax(Wi_y))
    write_curve('fig7C_nested', Wn_x, Wn_y * sC, 'nested W incl. non-selective atom')
    write_curve('fig7C_iid', Wi_x, Wi_y * sC, 'iid W')

    # (D) remaining borrowers -----------------------------------------------
    sD = 0.9                       # G(1) = 1 -> 0.9, as the prior height elsewhere
    aN = np.concatenate([nested['alphas_R1'], nested['alphas_R2']])
    Gn = np.concatenate([nested['GLOs_R1'], nested['GLOs_R2']])
    Bn = np.concatenate([nested['BLOs_R1'], nested['BLOs_R2']])
    write_curve('fig7D_nested_G', aN, Gn * sD, 'nested remaining good')
    write_curve('fig7D_nested_B', aN, Bn * sD, 'nested remaining bad')
    write_curve('fig7D_iid_G', ae, iid['G_eq'] * sD, 'iid remaining good')
    write_curve('fig7D_iid_B', ae, iid['B_eq'] * sD, 'iid remaining bad')

    marks = {
        'figSevAlphaZero': (a0, a0),
        'figSevAlphaOne': (a1, a1),
        'figSevAlphaTwo': (a2, a2),
        'figSevAlphaBar': (iid['alpha_bar'], iid['alpha_bar']),
        'figSevRp': (rp * sA, rp),
        'figSevRNS': (rNS * sA, rNS),
        'figSevKOne': (K1 * sA, K1),
        'figSevAvgNested': (avg_n * sA, avg_n),
        'figSevAvgIID': (avg_i * sA, avg_i),
        'figSevGammaOne': (1.0 * sB, 1.0),
        'figSevGammaNS': (gNS * sB, gNS),
        'figSevGammaZero': (nested['gammas_R1'][0] * sB, nested['gammas_R1'][0]),
        'figSevWNS': (WNS * sC, WNS),
        'figSevWNestedEnd': (Wn_y[-1] * sC, Wn_y[-1]),
        'figSevWIIDEnd': (Wi_y[-1] * sC, Wi_y[-1]),
        'figSevGOne': (1.0 * sD, 1.0),
        'figSevBOne': (params.BperG * sD, params.BperG),
        'figSevGNestedEnd': (Gn[-1] * sD, Gn[-1]),
        'figSevBNestedEnd': (Bn[-1] * sD, Bn[-1]),
        'figSevGIIDEnd': (iid['G_eq'][-1] * sD, iid['G_eq'][-1]),
        'figSevBIIDEnd': (iid['B_eq'][-1] * sD, iid['B_eq'][-1]),
    }
    write_marks('fig7_marks.tex', marks,
                'fig:nested-vs-iid -- Parameters() baseline of credit_model.py')
    return marks


# ---------------------------------------------------------------------------
# Figure fig:density_limit, bottom row
# ---------------------------------------------------------------------------
def export_fig6(n_curves=6):
    params = cm.Parameters(Pi=0.235, beta=0.5, BperG=1.0)
    cost = (9.0, 2.0, 0.2, 1.0)            # as in credit_model.main()
    saved = (cm.COST_C2, cm.COST_P2, cm.COST_C1, cm.COST_P1)
    cm.COST_C2, cm.COST_P2, cm.COST_C1, cm.COST_P1 = cost
    try:
        snaps = cm.nested_density_snapshots(params, n_curves=n_curves)
    finally:
        cm.COST_C2, cm.COST_P2, cm.COST_C1, cm.COST_P1 = saved

    om = snaps['omvec']
    a0, a1, beta = snaps['alpha0'], snaps['alpha1'], snaps['beta']
    og0, og1 = beta + (1 - beta) * a0, beta + (1 - beta) * a1
    ob0, ob1 = (1 - beta) + beta * a0, (1 - beta) + beta * a1
    sY = 0.9                                  # density 1 -> prior height 0.9

    print('Figure density_limit (bottom row)')
    print(f'  alpha0={a0:.4f} alpha1={a1:.4f} snapshots at {np.round(snaps["alphas"], 3)}')

    for k in range(n_curves):
        write_curve(f'fig6_bad_{k}', om, snaps['b_snaps'][k] * sY,
                    f'bad density after alpha={snaps["alphas"][k]:.4f}')
        write_curve(f'fig6_good_{k}', om, snaps['g_snaps'][k] * sY,
                    f'good density after alpha={snaps["alphas"][k]:.4f}')

    marks = {
        'figSixOmegaBZero': (ob0, ob0),
        'figSixOmegaBOne': (ob1, ob1),
        'figSixOmegaGZero': (og0, og0),
        'figSixOmegaGOne': (og1, og1),
        'figSixPrior': (sY, 1.0),
    }
    write_marks('fig6_marks.tex', marks,
                'fig:density_limit bottom row -- Pi=0.235, beta=0.5, BperG=1, '
                'cost 9a^2+0.2a')
    return marks


if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    export_fig7()
    export_fig6()
    files = sorted(f for f in os.listdir(OUT) if f.endswith(('.dat', '.tex')))
    print(f'Wrote {len(files)} files to {OUT}')
    for f in files:
        n = sum(1 for line in open(os.path.join(OUT, f)) if not line.startswith(('#', '%')))
        print(f'  {f:28s} {n:5d} lines')
